baseURL = "rims-bethune.github.io/website/"
languageCode = "fr"
title = "LP RIMS (MRIT) Béthune"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Infos"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Lire les informations'
  homepage_intro = 'La licence professionnelle Réseaux Informatiques, Mobilité, Sécurité'
 
  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "LP RIMS (MRIT) Béthune"
    meta_twitter_creator = "@sohaibafifi"

  [params.logo]
      mobile = "/img/neticien_blue.png"
      standard  = "/img/neticien_blue.png"
